<?php

namespace App\Helpers;

class CountryList
{
    public static function all()
    {
        $countries = [
            ['id' => 1, 'name' => 'Afghanistan', 'phonecode' => '93'],
            ['id' => 2, 'name' => 'Albania', 'phonecode' => '355'],
            ['id' => 3, 'name' => 'Algeria', 'phonecode' => '213'],
            ['id' => 4, 'name' => 'Andorra', 'phonecode' => '376'],
            ['id' => 5, 'name' => 'Angola', 'phonecode' => '244'],
            ['id' => 6, 'name' => 'Antigua and Barbuda', 'phonecode' => '1-268'],
            ['id' => 7, 'name' => 'Argentina', 'phonecode' => '54'],
            ['id' => 8, 'name' => 'Armenia', 'phonecode' => '374'],
            ['id' => 9, 'name' => 'Australia', 'phonecode' => '61'],
            ['id' => 10, 'name' => 'Austria', 'phonecode' => '43'],
            ['id' => 11, 'name' => 'Azerbaijan', 'phonecode' => '994'],
            ['id' => 12, 'name' => 'Bahamas', 'phonecode' => '1-242'],
            ['id' => 13, 'name' => 'Bahrain', 'phonecode' => '973'],
            ['id' => 14, 'name' => 'Bangladesh', 'phonecode' => '880'],
            ['id' => 15, 'name' => 'Barbados', 'phonecode' => '1-246'],
            ['id' => 16, 'name' => 'Belarus', 'phonecode' => '375'],
            ['id' => 17, 'name' => 'Belgium', 'phonecode' => '32'],
            ['id' => 18, 'name' => 'Belize', 'phonecode' => '501'],
            ['id' => 19, 'name' => 'Benin', 'phonecode' => '229'],
            ['id' => 20, 'name' => 'Bhutan', 'phonecode' => '975'],
            ['id' => 21, 'name' => 'Bolivia', 'phonecode' => '591'],
            ['id' => 22, 'name' => 'Bosnia and Herzegovina', 'phonecode' => '387'],
            ['id' => 23, 'name' => 'Botswana', 'phonecode' => '267'],
            ['id' => 24, 'name' => 'Brazil', 'phonecode' => '55'],
            ['id' => 25, 'name' => 'Brunei', 'phonecode' => '673'],
            ['id' => 26, 'name' => 'Bulgaria', 'phonecode' => '359'],
            ['id' => 27, 'name' => 'Burkina Faso', 'phonecode' => '226'],
            ['id' => 28, 'name' => 'Burundi', 'phonecode' => '257'],
            ['id' => 29, 'name' => 'Cambodia', 'phonecode' => '855'],
            ['id' => 30, 'name' => 'Cameroon', 'phonecode' => '237'],
            ['id' => 31, 'name' => 'Canada', 'phonecode' => '1'],
            ['id' => 32, 'name' => 'Cape Verde', 'phonecode' => '238'],
            ['id' => 33, 'name' => 'Cayman Islands', 'phonecode' => '1-345'],
            ['id' => 34, 'name' => 'Central African Republic', 'phonecode' => '236'],
            ['id' => 35, 'name' => 'Chad', 'phonecode' => '235'],
            ['id' => 36, 'name' => 'Chile', 'phonecode' => '56'],
            ['id' => 37, 'name' => 'China', 'phonecode' => '86'],
            ['id' => 38, 'name' => 'Colombia', 'phonecode' => '57'],
            ['id' => 39, 'name' => 'Comoros', 'phonecode' => '269'],
            ['id' => 40, 'name' => 'Costa Rica', 'phonecode' => '506'],
            ['id' => 41, 'name' => 'Croatia', 'phonecode' => '385'],
            ['id' => 42, 'name' => 'Cuba', 'phonecode' => '53'],
            ['id' => 43, 'name' => 'Cyprus', 'phonecode' => '357'],
            ['id' => 44, 'name' => 'Czech Republic', 'phonecode' => '420'],
            ['id' => 45, 'name' => 'Denmark', 'phonecode' => '45'],
            ['id' => 46, 'name' => 'Djibouti', 'phonecode' => '253'],
            ['id' => 47, 'name' => 'Dominica', 'phonecode' => '1-767'],
            ['id' => 48, 'name' => 'Dominican Republic', 'phonecode' => '1-809'],
            ['id' => 49, 'name' => 'Ecuador', 'phonecode' => '593'],
            ['id' => 50, 'name' => 'Egypt', 'phonecode' => '20'],
            ['id' => 51, 'name' => 'El Salvador', 'phonecode' => '503'],
            ['id' => 52, 'name' => 'Estonia', 'phonecode' => '372'],
            ['id' => 53, 'name' => 'Eswatini', 'phonecode' => '268'],
            ['id' => 54, 'name' => 'Ethiopia', 'phonecode' => '251'],
            ['id' => 55, 'name' => 'Fiji', 'phonecode' => '679'],
            ['id' => 56, 'name' => 'Finland', 'phonecode' => '358'],
            ['id' => 57, 'name' => 'France', 'phonecode' => '33'],
            ['id' => 58, 'name' => 'Gabon', 'phonecode' => '241'],
            ['id' => 59, 'name' => 'Gambia', 'phonecode' => '220'],
            ['id' => 60, 'name' => 'Georgia', 'phonecode' => '995'],
            ['id' => 61, 'name' => 'Germany', 'phonecode' => '49'],
            ['id' => 62, 'name' => 'Ghana', 'phonecode' => '233'],
            ['id' => 63, 'name' => 'Greece', 'phonecode' => '30'],
            ['id' => 64, 'name' => 'Grenada', 'phonecode' => '1-473'],
            ['id' => 65, 'name' => 'Guatemala', 'phonecode' => '502'],
            ['id' => 66, 'name' => 'Guinea', 'phonecode' => '224'],
            ['id' => 67, 'name' => 'Guinea-Bissau', 'phonecode' => '245'],
            ['id' => 68, 'name' => 'Guyana', 'phonecode' => '592'],
            ['id' => 69, 'name' => 'Haiti', 'phonecode' => '509'],
            ['id' => 70, 'name' => 'Honduras', 'phonecode' => '504'],
            ['id' => 71, 'name' => 'Hungary', 'phonecode' => '36'],
            ['id' => 72, 'name' => 'Iceland', 'phonecode' => '354'],
            ['id' => 73, 'name' => 'India', 'phonecode' => '91'],
            ['id' => 74, 'name' => 'Indonesia', 'phonecode' => '62'],
            ['id' => 75, 'name' => 'Iran', 'phonecode' => '98'],
            ['id' => 76, 'name' => 'Iraq', 'phonecode' => '964'],
            ['id' => 77, 'name' => 'Ireland', 'phonecode' => '353'],
            ['id' => 78, 'name' => 'Israel', 'phonecode' => '972'],
            ['id' => 79, 'name' => 'Italy', 'phonecode' => '39'],
            ['id' => 80, 'name' => 'Jamaica', 'phonecode' => '1-876'],
            ['id' => 81, 'name' => 'Japan', 'phonecode' => '81'],
            ['id' => 82, 'name' => 'Jordan', 'phonecode' => '962'],
            ['id' => 83, 'name' => 'Kazakhstan', 'phonecode' => '7'],
            ['id' => 84, 'name' => 'Kenya', 'phonecode' => '254'],
            ['id' => 85, 'name' => 'Kuwait', 'phonecode' => '965'],
            ['id' => 86, 'name' => 'Kyrgyzstan', 'phonecode' => '996'],
            ['id' => 87, 'name' => 'Laos', 'phonecode' => '856'],
            ['id' => 88, 'name' => 'Latvia', 'phonecode' => '371'],
            ['id' => 89, 'name' => 'Lebanon', 'phonecode' => '961'],
            ['id' => 90, 'name' => 'Lesotho', 'phonecode' => '266'],
            ['id' => 91, 'name' => 'Liberia', 'phonecode' => '231'],
            ['id' => 92, 'name' => 'Libya', 'phonecode' => '218'],
            ['id' => 93, 'name' => 'Liechtenstein', 'phonecode' => '423'],
            ['id' => 94, 'name' => 'Lithuania', 'phonecode' => '370'],
            ['id' => 95, 'name' => 'Luxembourg', 'phonecode' => '352'],
            ['id' => 96, 'name' => 'Malaysia', 'phonecode' => '60'],
            ['id' => 97, 'name' => 'Maldives', 'phonecode' => '960'],
            ['id' => 98, 'name' => 'Malta', 'phonecode' => '356'],
            ['id' => 99, 'name' => 'Mauritius', 'phonecode' => '230'],
            ['id' => 100, 'name' => 'Mexico', 'phonecode' => '52'],
            ['id' => 101, 'name' => 'Moldova', 'phonecode' => '373'],
            ['id' => 102, 'name' => 'Monaco', 'phonecode' => '377'],
            ['id' => 103, 'name' => 'Mongolia', 'phonecode' => '976'],
            ['id' => 104, 'name' => 'Montenegro', 'phonecode' => '382'],
            ['id' => 105, 'name' => 'Morocco', 'phonecode' => '212'],
            ['id' => 106, 'name' => 'Mozambique', 'phonecode' => '258'],
            ['id' => 107, 'name' => 'Myanmar', 'phonecode' => '95'],
            ['id' => 108, 'name' => 'Namibia', 'phonecode' => '264'],
            ['id' => 109, 'name' => 'Nepal', 'phonecode' => '977'],
            ['id' => 110, 'name' => 'Netherlands', 'phonecode' => '31'],
            ['id' => 111, 'name' => 'New Zealand', 'phonecode' => '64'],
            ['id' => 112, 'name' => 'Nicaragua', 'phonecode' => '505'],
            ['id' => 113, 'name' => 'Niger', 'phonecode' => '227'],
            ['id' => 114, 'name' => 'Nigeria', 'phonecode' => '234'],
            ['id' => 115, 'name' => 'Norway', 'phonecode' => '47'],
            ['id' => 116, 'name' => 'Oman', 'phonecode' => '968'],
            ['id' => 117, 'name' => 'Pakistan', 'phonecode' => '92'],
            ['id' => 118, 'name' => 'Panama', 'phonecode' => '507'],
            ['id' => 119, 'name' => 'Papua New Guinea', 'phonecode' => '675'],
            ['id' => 120, 'name' => 'Paraguay', 'phonecode' => '595'],
        ];

        return collect(array_map(function ($country) {
            return (object) $country;
        }, $countries));
    }
}
